### ISSUE TITLE
run the models on your own hardware. But how?

### ISSUE THREAD

**Issue by nitinmukesh** [replicate/cog-flux#36]
> The code in this repo can be used as a template for customizations on FLUX.1, or to run the models on your own hardware.

Any installation steps available to install on local.

**Comment by Viper373** [comment]
> > The code in this repo can be used as a template for customizations on FLUX.1, or to run the models on your own hardware.此存储库中的代码可用作 FLUX.1 上自定义的模板，或在您自己的硬件上运行模型。
> 
> Any installation steps available to install on local.可在本地安装的任何安装步骤。

I also want to know, please!

**Comment by goyalpramod** [comment]
Hey guys so there are a few steps you would need to do. (I believe these should work, Unable to try atm because I do not have linux installed)

* Setup linux 
* There is a cog.yaml.template file, copy that and just make a cog.yaml 
* Setup a DockerFile using that. Here is a [link](https://cog.run/getting-started/) to a guide 
* if you go to samples.py you can see some code that runs it. That can help you figure out how to run it locally.

**Comment by nitinmukesh** [comment]
No support for Windows :(
